# Script to deploy on the Render cloud platform
#Pipeline that deploys to the Render cloud platform
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:.github/workflows/render-deploy.yml

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2

      - name: Invoke deployment hook
        uses: distributors/workflow-webhook@v2
        env: 
          webhook_url: "https://api.render.com/deploy/srv-cioe9sdph6elhbscov8g?key=oZBAi1wUPwU"
          webhook secrets: "oZBAi1wUPwU"

      - uses: bounceapp/render-action@0.6.0        
        with:
          render-token: ${{secrets.RENDER_API_KEY}}
          github-token: ${{secrets.ACC_API_KEY}} # This is the GitHub token
          service-id: "srv-cioe9sdph6elhbscov8g" # This id is unique for each app
          retries: 20
          wait: 16000
          sleep: 30000